# Generated by Django 3.2.25 on 2024-06-12 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('enterprise', 'ENTERPRISE'), ('government', 'GOVERNMENT')], default='ENTERPRISE', max_length=15)),
                ('incidentId', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('detail', models.TextField(max_length=300)),
                ('priority', models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], default='HIGH', max_length=6)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('inprogress', 'INPROGRESS'), ('closed', 'CLOSED')], default='OPEN', max_length=20)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
